import puppeteer from 'puppeteer-core';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const url=process.env.TEST_URL||'http://127.0.0.1:5194',out=process.env.TEST_OUT||'artifacts/ipad-cinema';await fs.mkdir(out,{recursive:true});
const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=metal']});
const wait=ms=>new Promise(r=>setTimeout(r,ms)),report={url,viewports:[],errors:[],limitations:['iPad dimensions and touch emulation on Mac Chrome; not a physical iPad.']};
try{
 for(const [width,height]of [[820,1180],[1180,820],[768,1024],[1024,768]]){
  const page=await browser.newPage();page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text())});
  await page.setViewport({width,height,deviceScaleFactor:1,isMobile:true,hasTouch:true});await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);
  await page.goto(`${url}/?debug=1`,{waitUntil:'networkidle0'});const row={width,height,checks:[]};report.viewports.push(row);
  const tap=async selector=>{await page.$eval(selector,e=>e.scrollIntoView({block:'center'}));const p=await page.$eval(selector,e=>{const r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}});await page.touchscreen.tap(p.x,p.y);await wait(80)};
  const state=()=>page.evaluate(()=>window.__CHESS_DEBUG__.state());
  const camera=()=>page.evaluate(()=>window.__CHESS_DEBUG__.camera());
  const square=async(s,h=.7)=>{const p=await page.evaluate(([s,h])=>window.__CHESS_DEBUG__.project(s,h),[s,h]);await page.touchscreen.tap(p.x,p.y);await wait(80)};
  await tap('#settings');assert.equal(await page.$eval('#setting-cinema',e=>e.checked),false);assert.equal(await page.$eval('#setting-motion',e=>e.checked),true);assert.match(await page.$eval('#cinema-status',e=>e.textContent),/減少動態/);row.checks.push('System Reduce Motion respected and cinema shown OFF with explanation');
  await tap('#setting-cinema');assert.equal((await state()).reduced,false);assert.equal(await page.$eval('#setting-motion',e=>e.checked),false);assert.equal(await page.$eval('#setting-cinema',e=>e.checked),true);assert.equal(await page.evaluate(()=>document.documentElement.classList.contains('reduced-motion')),false);await tap('[data-close]');row.checks.push('One touch enables cinema and synchronizes both switches and CSS motion');
  const before=await camera();await square('e2');await square('e4',.02);await wait(600);const during=await camera();assert(await page.$eval('#stage',e=>e.classList.contains('cinematic')));assert(Math.hypot(...during.position.map((x,i)=>x-before.position[i]))>5);assert(during.distance<before.distance*.6);await page.screenshot({path:`${out}/${width}x${height}-move.png`});await page.waitForFunction(()=>!window.__CHESS_DEBUG__.state().animating,{timeout:12000});assert.deepEqual((await state()).history,['e4']);row.checks.push('Real touch e2→e4 visibly moves camera close, plays full film, restores board view');
  await tap('#settings');await tap('#setting-motion');assert.equal(await page.$eval('#setting-cinema',e=>e.checked),false);await tap('[data-close]');const fixed=await camera();await square('e7');await square('e5',.02);await wait(150);assert.equal(await page.$eval('#stage',e=>e.classList.contains('cinematic')),false);assert.deepEqual((await camera()).position,fixed.position);await page.waitForFunction(()=>!window.__CHESS_DEBUG__.state().animating);row.checks.push('Choosing Reduce Motion restores fixed camera without a misleading ON state');
  await tap('#cinema');assert.equal((await state()).reduced,false);await tap('#settings');await tap('#demo');await wait(850);await square('d4');await square('d6');await wait(650);assert(await page.$eval('#stage',e=>e.classList.contains('cinematic')));await page.screenshot({path:`${out}/${width}x${height}-charge.png`});await wait(1400);await page.screenshot({path:`${out}/${width}x${height}-attack.png`});await page.waitForFunction(()=>!window.__CHESS_DEBUG__.state().animating,{timeout:12000});assert.equal((await state()).pieces,5);row.checks.push('Toolbar re-enables film; real touch chariot capture plays through and removes target');row.camera={before,during};await page.close();
 }
 const page=await browser.newPage();await page.setViewport({width:820,height:1180,isMobile:true,hasTouch:true});await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);
 await page.goto(url,{waitUntil:'networkidle0'});await page.evaluate(()=>localStorage.setItem('imperium-settings',JSON.stringify({cinematic:true,reduced:true,muted:false,volume:.65})));await page.reload({waitUntil:'networkidle0'});
 const tap=async s=>{const p=await page.$eval(s,e=>{const r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}});await page.touchscreen.tap(p.x,p.y);await wait(80)};
 await tap('#settings');assert.equal(await page.$eval('#setting-cinema',e=>e.checked),false);await tap('#setting-cinema');await page.reload({waitUntil:'networkidle0'});await tap('#settings');assert.equal(await page.$eval('#setting-cinema',e=>e.checked),true);assert.equal(await page.$eval('#setting-motion',e=>e.checked),false);assert.equal(await page.evaluate(()=>matchMedia('(prefers-reduced-motion:reduce)').matches),true);assert.equal(await page.evaluate(()=>!!window.__CHESS_DEBUG__),false);report.persistence='Existing conflicting preference is displayed honestly; explicit enable persists after reload while OS Reduce Motion remains enabled';await page.close();assert.deepEqual(report.errors,[]);
}finally{await fs.writeFile(`${out}/report.json`,JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report));}
