import puppeteer from 'puppeteer-core';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const url=process.env.TEST_URL||'http://127.0.0.1:5189',out='artifacts/mobile-release';await fs.mkdir(out,{recursive:true});
const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=metal']});
const report={url,input:'Chrome touchscreen.tap and CDP Input.dispatchTouchEvent; no mouse input',viewports:[],errors:[],limitations:['Chrome phone emulation verifies touch and layout, not real-device Safari behavior, thermal throttling, or phone GPU performance.']};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
let page;
try{for(const [width,height]of[[390,844],[844,390],[360,640]]){
 page=await browser.newPage();await page.setViewport({width,height,deviceScaleFactor:1,isMobile:true,hasTouch:true});const cdp=await page.createCDPSession(),checks=[],viewportReport={width,height,checks};report.viewports.push(viewportReport);
 page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text())});
 await page.evaluateOnNewDocument(()=>{window.__touchAudit=[];addEventListener('pointerup',e=>window.__touchAudit.push(e.pointerType));const AC=window.AudioContext;window.__contexts=[];window.AudioContext=class extends AC{constructor(...a){super(...a);window.__contexts.push(this)}}});
 await page.goto(`${url}/?debug=1`,{waitUntil:'networkidle0'});await page.waitForFunction(()=>window.__CHESS_DEBUG__);await wait(250);
 const state=()=>page.evaluate(()=>window.__CHESS_DEBUG__.state());
 const camera=()=>page.evaluate(()=>window.__CHESS_DEBUG__.camera());
 async function tap(selector){await page.$eval(selector,e=>e.scrollIntoView({block:'center'}));const r=await page.$eval(selector,e=>{const r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}});await page.touchscreen.tap(r.x,r.y);await wait(100);}
 async function square(s,h=.7){const p=await page.evaluate(([s,h])=>window.__CHESS_DEBUG__.project(s,h),[s,h]);assert(p.x>0&&p.x<width&&p.y>0&&p.y<height,`square ${s} offscreen`);await page.touchscreen.tap(p.x,p.y);await wait(100);}
 async function move(from,to,piece=false,skip=true){await square(from);assert.equal((await state()).selected,from);assert((await state()).legal.includes(to));await square(to,piece?.7:.02);assert.equal((await state()).animating,true);if(skip)await tap('#skip');else await page.waitForFunction(()=>!window.__CHESS_DEBUG__.state().animating,{timeout:10000});await wait(100);}
 const layout=await page.evaluate(()=>{const targets=[...document.querySelectorAll('.top-actions button,.view-tools button')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.height}).map(e=>{const r=e.getBoundingClientRect();return{id:e.id,width:r.width,height:r.height}});const cells=[];for(const f of'abcdefgh')for(let r=1;r<=8;r++){const s=f+r,p=window.__CHESS_DEBUG__.project(s,.02),e=document.elementFromPoint(p.x,p.y);if(e?.tagName!=='CANVAS')cells.push({square:s,blockedBy:e?.id||e?.tagName});}return{targets,blockedCells:cells,documentWidth:document.documentElement.scrollWidth,viewport:innerWidth};});
 viewportReport.layout=layout;assert(layout.targets.every(t=>t.width>=44&&t.height>=44));assert.equal(layout.documentWidth,layout.viewport);assert.deepEqual(layout.blockedCells,[]);checks.push('All 64 board cells unobstructed; visible top/board controls at least 44 px; no horizontal overflow');
 await page.screenshot({path:`${out}/${width}x${height}-board.png`});
 await square('e2');assert.deepEqual((await state()).legal.sort(),['e3','e4']);await square('e2');assert.equal((await state()).selected,null);await square('e2');await tap('#cancel-selection');assert.equal((await state()).selected,null);checks.push('Tap selects, repeated tap cancels, explicit Cancel cancels');
 await square('e2');const original=await camera(),p=await page.evaluate(()=>window.__CHESS_DEBUG__.project('e2',.7));
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:p.x,y:p.y,id:1}]});for(const shift of[25,50,75,50,25,0]){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:p.x+shift,y:p.y,id:1}]});await wait(25);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await wait(100);assert.equal((await state()).selected,'e2');assert.equal((await state()).history.length,0);assert.notDeepEqual((await camera()).position,original.position);checks.push('Out-and-back drag rotates camera without accidentally selecting or moving');
 await tap('#reset-camera');await wait(850);const beforePinch=await camera();const center=await page.$eval('canvas',e=>{const r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}});
 const points=d=>[{x:center.x-d,y:center.y,id:1},{x:center.x+d,y:center.y,id:2}];await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:points(45)});for(const d of[50,58,65,72,80]){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:points(d)});await wait(35);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await wait(100);assert(Math.abs((await camera()).distance-beforePinch.distance)>.5);assert.equal((await state()).selected,'e2');assert.equal((await state()).history.length,0);checks.push('Two-finger pinch zooms with no accidental move');
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:center.x,y:center.y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await tap('#reset-camera');await wait(850);await tap('#cancel-selection');await square('e2');assert.equal((await state()).selected,'e2');await tap('#cancel-selection');checks.push('Cancelled touch releases interaction; next tap still works');
 await move('e2','e4');await move('d7','d5');await square('e4');await page.screenshot({path:`${out}/${width}x${height}-capture-choice.png`});await square('d5');assert((await state()).animating);await wait(1900);await page.screenshot({path:`${out}/${width}x${height}-cinematic.png`});await page.waitForFunction(()=>!window.__CHESS_DEBUG__.state().animating,{timeout:10000});assert.deepEqual((await state()).history,['e4','d5','exd5']);assert.equal((await state()).pieces,31);assert.equal((await state()).turn,'b');checks.push('Actual touch opening e4 d5 exd5 and full cinematic capture');
 await tap('#undo');assert.deepEqual((await state()).history,['e4','d5']);assert.equal((await state()).pieces,32);checks.push('Touch Undo restores captured piece and correct turn');
 await tap('#flip');await wait(850);assert((await camera()).position[2]<0);await tap('#flip');await wait(850);assert((await camera()).position[2]>0);checks.push('Touch Flip and Overview camera controls work');
 await tap('#settings');await page.screenshot({path:`${out}/${width}x${height}-settings.png`});const fenBefore=(await state()).fen;
 for(const mode of['enhanced','basic']){await tap(`#graphics-${mode}`);assert.equal(await page.$eval(`#graphics-${mode}`,e=>e.getAttribute('aria-pressed')),'true');assert.equal((await state()).fen,fenBefore);}checks.push('Basic/enhanced lighting switch keeps the same game');
 await tap('#setting-motion');assert.equal((await state()).reduced,true);await tap('#setting-motion');assert.equal((await state()).reduced,false);await tap('[data-close]');
 await page.evaluate(()=>window.__CHESS_DEBUG__.load('7k/P7/8/8/8/8/8/7K w - - 0 1'));await square('a7');await square('a8',.02);assert.equal(await page.$eval('#modal',e=>e.hidden),false);const choices=await page.$$eval('[data-promotion]',els=>els.map(e=>{const r=e.getBoundingClientRect();return{width:r.width,height:r.height,bottom:r.bottom}}));assert.equal(choices.length,4);assert(choices.every(c=>c.width>=44&&c.height>=44&&c.bottom<height));
 await page.screenshot({path:`${out}/${width}x${height}-promotion.png`});await tap('[data-promotion="q"]');await tap('#skip');assert.equal((await state()).fen.split(' ')[0][0],'Q');checks.push('Promotion exposes 4 reachable touch choices and creates chosen queen');
 await tap('#settings');await tap('#settings-new');await tap('#confirm-new');await wait(850);assert.equal((await state()).pieces,32);assert.equal((await state()).history.length,0);checks.push('Settings → New game → confirmation resets to 32 pieces');
 const rotated={width:height,height:width,deviceScaleFactor:1,isMobile:true,hasTouch:true};await page.setViewport(rotated);await wait(500);assert.equal((await state()).history.length,0);await page.setViewport({width,height,deviceScaleFactor:1,isMobile:true,hasTouch:true});await wait(500);await square('g1');assert.equal((await state()).selected,'g1');checks.push('Orientation round-trip preserves game and touch picking');
 const audit=await page.evaluate(()=>({pointerTypes:[...new Set(window.__touchAudit)],audio:window.__contexts.map(c=>c.state),diagnostics:window.__THREE_GAME_DIAGNOSTICS__}));assert.deepEqual(audit.pointerTypes,['touch']);assert(audit.audio.includes('running'));viewportReport.audit=audit;await page.close();
 }}catch(error){report.failure=String(error);if(page&&!page.isClosed())await page.screenshot({path:`${out}/failure.png`});throw error;}finally{await fs.writeFile(`${out}/mobile-playtest.json`,JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({viewports:report.viewports.map(v=>({width:v.width,height:v.height,checks:v.checks})),errors:report.errors,failure:report.failure},null,2));}
assert.deepEqual(report.errors,[]);
