import puppeteer from 'puppeteer-core';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const out='artifacts/release-check';await fs.mkdir(out,{recursive:true});
const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=metal']});
const page=await browser.newPage();await page.setViewport({width:1440,height:940,deviceScaleFactor:1});
const errors=[],results=[],motion=[];page.on('pageerror',e=>{errors.push(String(e));console.log('ERROR',String(e))});page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.evaluateOnNewDocument(()=>{const AC=window.AudioContext;window.__audioContexts=[];window.AudioContext=class extends AC{constructor(...args){super(...args);window.__audioContexts.push(this)}createGain(){const g=super.createGain();(window.__audioGains??=[]).push(g);return g}}});
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const state=()=>page.evaluate(()=>window.__CHESS_DEBUG__.state());
async function shot(name){await page.screenshot({path:`${out}/${name}.png`});}
async function clickSquare(square,piece=false){const p=await page.evaluate(([s,h])=>window.__CHESS_DEBUG__.project(s,h),[square,piece?.7:.02]);await page.mouse.click(p.x,p.y);await wait(80);}
async function finish(){await page.keyboard.press('Space');await wait(90);}
async function move(from,to,skip=true){await clickSquare(from,true);assert.equal((await state()).selected,from,`select ${from}`);assert.ok((await state()).legal.includes(to),`${from}-${to} legal`);await clickSquare(to,!!(await page.evaluate(s=>window.__CHESS_DEBUG__.pieceStats().some(p=>p.square===s),to)));if(skip)await finish();}
try{
await page.goto('http://127.0.0.1:5188/?debug=1',{waitUntil:'networkidle0'});await page.waitForFunction(()=>window.__CHESS_DEBUG__);await wait(150);await shot('initial-desktop');
await clickSquare('e2',true);assert.deepEqual((await state()).legal.sort(),['e3','e4']);await clickSquare('e5');assert.equal((await state()).history.length,0);results.push('Illegal destination rejected');
await move('e2','e4');await move('e7','e5');await move('g1','f3');assert.equal((await state()).turn,'b');results.push('Opening moves e4 e5 Nf3 through real pointer input');
await page.click('#undo');assert.equal((await state()).history.length,2);results.push('Undo restores prior turn and pieces');
await page.evaluate(()=>window.__THREE_GAME_TEST_HOOKS__.setState('threat-preview'));assert.deepEqual((await state()).fears.sort(),['b4','d6','g4']);await wait(250);await shot('all-three-afraid');
await page.keyboard.press('Escape');assert.equal((await state()).relief.length,3);await wait(450);await shot('all-three-relieved');results.push('All 3 legal targets fear; cancellation triggers relief');await wait(1100);assert.equal((await state()).relief.length,0);
await clickSquare('d4',true);await clickSquare('g4',true);assert.equal((await state()).animating,true);assert.deepEqual((await state()).relief.sort(),['b4','d6']);
for(let i=0;i<13;i++){await wait(210);await shot(`attack-${String(i).padStart(2,'0')}`);motion.push({frame:i,...await state(),diagnostics:await page.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__)});}
await page.waitForFunction(()=>!window.__CHESS_DEBUG__.state().animating);assert.equal((await state()).pieces,5);results.push('Chariot cinematic capture completed, spared targets relieve, victim removed');
await page.evaluate(()=>window.__CHESS_DEBUG__.load('r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1'));await move('e1','g1');assert.equal((await state()).fen.split(' ')[0].split('/').at(-1),'R4RK1');results.push('Kingside castling moves king and rook');
await page.evaluate(()=>window.__CHESS_DEBUG__.load('4k3/8/8/3pP3/8/8/8/4K3 w - d6 0 1'));await clickSquare('e5',true);assert.ok((await state()).fears.includes('d5'));await clickSquare('d6');await finish();assert.equal((await state()).pieces,3);results.push('En passant marks victim and removes d5 pawn');
await page.evaluate(()=>window.__CHESS_DEBUG__.load('7k/P7/8/8/8/8/8/7K w - - 0 1'));await clickSquare('a7',true);await clickSquare('a8');assert.equal(await page.$eval('#modal',e=>e.hidden),false);await page.click('[data-promotion="n"]');await finish();assert.equal((await state()).fen.split(' ')[0][0],'N');results.push('Promotion dialog honors knight underpromotion');
await page.evaluate(()=>window.__CHESS_DEBUG__.load('k3r3/8/8/8/8/8/4R3/4K3 w - - 0 1'));await clickSquare('e2',true);assert.ok((await state()).legal.every(s=>s[0]==='e'));results.push('Pinned rook cannot expose its king');
await page.evaluate(()=>window.__CHESS_DEBUG__.load('rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'));for(const [f,t]of [['f2','f3'],['e7','e5'],['g2','g4'],['d8','h4']])await move(f,t);await wait(550);assert.equal((await state()).gameOver,true);assert.ok((await page.$eval('#modal',e=>e.textContent)).includes('黑曜軍團獲勝'));await shot('checkmate');await page.click('#rematch');assert.equal((await state()).pieces,32);assert.equal((await state()).history.length,0);results.push('Fools mate triggers result and rematch resets game');
await page.click('#sound');assert.equal((await state()).muted,true);await page.click('#sound');assert.equal((await state()).muted,false);const audio=await page.evaluate(()=>window.__audioContexts.map(c=>({state:c.state,sampleRate:c.sampleRate})));assert.ok(audio.some(c=>c.state==='running'));const energy=await page.evaluate(async()=>{const ctx=window.__audioContexts[0],a=ctx.createAnalyser();a.fftSize=2048;window.__audioGains[0].connect(a);await new Promise(r=>setTimeout(r,120));const b=new Float32Array(a.fftSize);a.getFloatTimeDomainData(b);return Math.sqrt(b.reduce((s,x)=>s+x*x,0)/b.length)});assert.ok(energy>0.000001);results.push('Real gesture unlocks audio; mute toggle works; nonzero synthesized audio signal');
await page.setViewport({width:390,height:844,deviceScaleFactor:1});await page.evaluate(()=>window.__THREE_GAME_TEST_HOOKS__.setState('active-play'));await wait(200);await shot('mobile-active');await page.keyboard.press('Escape');await clickSquare('d2',true);assert.equal((await state()).selected,'d2');await clickSquare('d4');await finish();assert.equal((await state()).turn,'b');results.push('Narrow viewport real pointer selection and move');
await fs.writeFile(`${out}/motion.json`,JSON.stringify(motion,null,2));await fs.writeFile(`${out}/playtest.json`,JSON.stringify({passed:results,errors,audio,motion,diagnostics:await page.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__)},null,2));console.log(JSON.stringify({passed:results,errors,audio},null,2));assert.equal(errors.length,0);
}catch(error){console.log('FAILED',String(error),await state().catch(()=>null));await shot('failure');await fs.writeFile(`${out}/failure.json`,JSON.stringify({error:String(error),errors,results},null,2));process.exitCode=1;}finally{await browser.close();}
